### PR TITLE
Feat: Auth (login and Signup) pages

### PR DESCRIPTION
**Pull request by Logan1x**
This PR includes HTML & CSS files for 
- login page
- signup page

### Deploy Preview :
- Login page:  https://deploy-preview-2--plethora-project.netlify.app/components/login.html
- Signup page: https://deploy-preview-2--plethora-project.netlify.app/components/signup.html

### Screenshots :

image
image

### CODE REVIEW

**Comment by shrey27** [comment]
I think your homepage has some issues with responsiveness. In mobile view content is overflowing and a horizontal scrollbar is getting active. Check the width and fluidity of all the elements that may be causing this issue.

**Review by shrey27 — APPROVED** [review]
Update the homepage before merging the PR.

**Comment by Logan1x** [comment]
> Update the homepage before merging the PR.

Hey @shrey27, I am currently not aiming for mobile responsiveness, If I'll time after all the features, I'll be back to this.

**Review by Hnh013 — APPROVED** [review]
loved the dark and light design , code is clean , good to merge!
A suggestion for future: if not using navbar you can remove nav tag in later iterations

**Comment by Logan1x** [comment]
> if not using navbar you can remove nav tag in later iterations
I didn't understand anything by this? 

are you talking about empty nav tags? They are not empty, I am filling data to them using nav.js file automatically instead of writing data each time.

**Comment by Logan1x** [comment]
Thanks @shrey27 & @Hnh013 , Merging the PR

**Pull request merged**
